# Generated by Django 4.2.3 on 2024-08-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
